<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ParityProof.Core\ParityProof.Core.csproj" />
    <InternalsVisibleTo Include="ParityProof.Engine.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspectInjector_Enabled>false</AspectInjector_Enabled>
  </PropertyGroup>

</Project>
