<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ParityProof.Core\ParityProof.Core.csproj" />
    <ProjectReference Include="..\ParityProof.Platform\ParityProof.Platform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspectInjector" Version="2.9.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
